var yarn_colours = [
{ name:"vanilla cream", hex:"ECD7C6"},
{ name:"dusty lilac", hex:"8C72AF"},
{ name:"pale lilac", hex:"C5B9DD"},
{ name:"dusty rose", hex:"DAC7DA"},
{ name:"tea rose", hex:"CC89BC", "danielles":true},
{ name:"rich mauve", hex:"5B3765"},
{ name:"dark aubergine", hex:"382042"},
{ name:"pansy purple", hex:"735490", "danielles":true},
{ name:"royal blue", hex:"1A2564"},
{ name:"dolphin blue", hex:"6888AF", "danielles":true},
{ name:"midnight blue", hex:"292A3F"},
{ name:"duck egg blue", hex:"CED4E4"},
{ name:"sky blue", hex:"57A1D7"},
{ name:"seafoam blue", hex:"DFE0E2"},
{ name:"washed teal", hex:"BFDDDF"},
{ name:"marine blue", hex:"39C2CE", "danielles":true},
{ name:"kingfisher blue", hex:"097EAF", "danielles":true},
{ name:"sailor blue", hex:"224A88"},
{ name:"grass green", hex:"49B464"},
{ name:"evergreen", hex:"046458"},
{ name:"racing green", hex:"334F38"},
{ name:"slate green", hex:"508E83"},
{ name:"spearmint green", hex:"7AC88A"},
{ name:"lime green", hex:"BCCE5E", "danielles":true},
{ name:"pistachio green", hex:"CBCDBF"},
{ name:"blood orange", hex:"F86B1B", "danielles":true},
{ name:"seville orange", hex:"F4A135"},
{ name:"melon sorbet", hex:"FBB985"},
{ name:"peach orange", hex:"F8C09F"},
{ name:"mandarin orange", hex:"FA9224"},
{ name:"rasperry pink", hex:"BA4A82", "danielles":true},
{ name:"candyfloss pink", hex:"DDBDCA"},
{ name:"bubblegum pink", hex:"E77C9C"},
{ name:"lipstick pink", hex:"EC466A"},
{ name:"ballet pink", hex:"F5D7DD"},
{ name:"blush pink", hex:"FBC7C9"},
{ name:"vintage pink", hex:"F3937D"},
{ name:"bright peach", hex:"FCA188"},
{ name:"red wine", hex:"B2203A"},
{ name:"pillar red", hex:"D9182F"},
{ name:"rose red", hex:"F1313C"},
{ name:"tomato red", hex:"E4392F", "danielles":true},
{ name:"mustard yellow", hex:"EFAD23"},
{ name:"buttercup yellow", hex:"F9C53E", "danielles":true},
{ name:"dafffodil yellow", hex:"FAD783"},
{ name:"banana cream", hex:"E9E1C9"},
{ name:"pure black", hex:"1C1C1E"},
{ name:"coffee bean", hex:"6C4536"},
{ name:"soft fudge", hex:"B48567"},
{ name:"granite grey", hex:"584F54"},
{ name:"slate grey", hex:"807D88", "danielles":true},
{ name:"stormy grey", hex:"BDBBBE", "danielles":true},
{ name:"misty grey", hex:"E2DCDE"},
{ name:"light caramel", hex:"EDCEB4"},
{ name:"champagne white", hex:"EFE7E5"},
{ name:"paper white", hex:"E9E6ED", "danielles":true}];
